### PR TITLE
Gentoo Installation Update

### PR DESCRIPTION
**Pull request by samuel-garmany**
Hopefully I did this right, the ebuild you've selected for openrazer lacks a necessary .config file, I've added a command to fetch the file from the source code, I used tux as the stand in username because that's what the gentoo handbook uses, feel free to change it.

### CODE REVIEW

**Comment by z3ntu** [comment]
The daemon creates copies over the example file from `/usr/share/openrazer/razer.conf.example` into `~/.config/openrazer/razer.conf` so this shouldn't be necessary to do.

**Comment by samuel-garmany** [comment]
> The daemon creates copies over the example file from `/usr/share/openrazer/razer.conf.example` into `~/.config/openrazer/razer.conf` so this shouldn't be necessary to do.

For the ebuild from the overlay you've selected, /usr/share/openrazer/razer.conf.example is empty. Though to be honest I still haven't gotten it fully working on gentoo.

**Comment by samuel-garmany** [comment]
I just did get it working, trust me you need that wget, change it curl if you please but that config is not present in the ebuild

**Comment by z3ntu** [comment]
Then the ebuild needs to be fixed as the daemon expects the file there.
I won't put workarounds for faulty disto packaging into the installation instructions.

**Comment by samuel-garmany** [comment]
I understand but I don't control or know how to fix an ebuild, fetching one file I can do. Would you be open to getting both polychromatic & openrazer from a different overlay & thus a different ebuild? Or you can use this wget, because as it stands the instructions are not complete.

**Comment by z3ntu** [comment]
I found https://github.com/vifino/vifino-overlay/issues/51 , that's the issue reported in the overlay. Please ask there for further support, as I mentioned I will not merge workarounds for broken packaging.

**Pull request closed without merging**
