### PR TITLE
Add documentation for NixOS support

### PR DESCRIPTION
**Pull request by evanjs**
- Document NixOS module
- Document `nix-shell` usage
- TODO: add "razer-fied" NixOS logo to imgs directory (cc @lah7)
[Here](https://github.com/NixOS/nixos-artwork/blob/376ed4ba8dc2e611b7e8a62fdc680967ead5bd87/logo/nix-snowflake.svg) is the official NixOS logo

Happy to ping nixos irc in case a review from another nixer would help.

### CODE REVIEW

**Comment by lah7** [comment]
:heavy_check_mark: **Razer-ified green logo added.**

Instructions seem good in terms of formatting, thank you.

Not being familiar with NixOS myself, I'd assume other Nixers would already understand how their packaging system works? For the **nix-shell** section, is this describing how to run the daemon? Would we need to describe how to auto start at login, for instance?

**Comment by evanjs** [comment]
> ✔️ **Razer-ified green logo added.**
> 
> Instructions seem good in terms of formatting, thank you.
> 
> Not being familiar with NixOS myself, I'd assume other Nixers would already understand how their packaging system works? For the **nix-shell** section, is this describing how to run the daemon? Would we need to describe how to auto start at login, for instance?

The `nix-shell` bit is merely about creating a development environment to fool around with the daemon in Python, etc. Often times it's as simple as `nix-shell -p package`, and I included instructions as this case is a little more involved, which is not uncommon for Python packages in NixOS because of the pure nature of the distro.  

There is no further setup required in terms of creating service files, as adding `hardware.openrazer.enable` to the user's configuration will take care of all of this. 

I'm going to check and see if `services.dbus.socketActivated` is required just in case, as one user had issues using the service until this was enabled.

**Comment by evanjs** [comment]
Okay! Tested it out, and I did _not_ need `services.dbus.socketActivated` on XMonad, so I think I'll just add that bit to the NixOS page for i3, which is what the user that needed to enable it (in order to query the daemon) was using.

With just the module enabled, before graphical login, the service was inactive, and started up once I logged in to my window manager, so I think the instructions are complete, at least in terms of OpenRazer specific configuration.

**Comment by lah7** [comment]
Good to know, thank you. The instructions shall go live. 👍

**Pull request merged**
