### PR TITLE
Deathadder 2000 icon loads through https

### PR DESCRIPTION
**Pull request by ninjamar**
The deathadder 2000 icon gets loaded through http. Viewing openrazer.github.io over https doesn't show the icon properly.
This PR fixes this issue.

### CODE REVIEW

**Comment by z3ntu** [comment]
Have you tried accessing the url? I'm getting this

image

**Review by lah7 — CHANGES_REQUESTED** [review]
Thanks for spotting. Looks like Chrome is unhappy since Firefox has no problem showing it over `http`. `https` would be better, but I get the security issue as well so we're kind of stuck, unless we can find a replacement image or the equivalent CDN URL.

This `_data/devices.yml` is generated from the daemon on every release. It would need correcting there in addition.

**Comment by ninjamar** [comment]
> Thanks for spotting. Looks like Chrome is unhappy since Firefox has no problem showing it over `http`. `https` would be better, but I get the security issue as well so we're kind of stuck, unless we can find a replacement image or the equivalent CDN URL.
> 
> This `_data/devices.yml` is generated from the daemon on every release. It would need correcting there in addition.

I'll make a PR for that. I think I found it

**Comment by ninjamar** [comment]
https://github.com/openrazer/openrazer/pull/1769

**Comment by lah7** [comment]
If we need an alternate image, here's a couple:

* https://assets2.razerzone.com/images/da10m/carousel/razer-death-adder-gallery-09.png
* https://assets2.razerzone.com/images/da10m/carousel/razer-death-adder-gallery-18.png (white model)

(via <https://www.razer.com/gb-en/pc/gaming-mice/deathadder-family>)

**Comment by ninjamar** [comment]
> If we need an alternate image, here's a couple:
> 
> * https://assets2.razerzone.com/images/da10m/carousel/razer-death-adder-gallery-09.png
> * https://assets2.razerzone.com/images/da10m/carousel/razer-death-adder-gallery-18.png (white model)
> 
> (via https://www.razer.com/gb-en/pc/gaming-mice/deathadder-family)

I used https://assets2.razerzone.com/images/da10m/carousel/razer-death-adder-gallery-09.png

**Review by lah7 — APPROVED** [review]

**Pull request merged**
